steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - hello-function
  - --region=us-west2
  - --source=./node-hello-function/
  - --trigger-http
  - --allow-unauthenticated
  - --gen2
  - --docker-registry=artifact-registry
  - --runtime=nodejs18
