steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - helloGET
  - --region=us-west2
  - --source=./node-hello-function/
  - --trigger-http
  - --runtime=nodejs18
