steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/docker-hello-world/gcp-ci-cd-demo', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/docker-hello-world/gcp-ci-cd-demo']
images: ['us-central1-docker.pkg.dev/${PROJECT_ID}/docker-hello-world/gcp-ci-cd-demo']